
[light_sources]
	water_sensitive_check = true
	block_entities = true
	entities = true
	self = true

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				axolotl = true
				bee = true
				egg = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				allay = true
				skeleton = true
				llama = true
				bat = true
				frog = true
				hoglin = true
				experience_bottle = true
				armadillo = true
				rabbit = true
				firework_rocket = true
				silverfish = true
				armor_stand = true
				drowned = true
				experience_orb = true
				dolphin = true
				item = true
				stray = true
				shulker = true
				turtle = true
				wandering_trader = true
				salmon = true
				wither_skeleton = true
				piglin_brute = true
				breeze = true
				goat = true
				ocelot = true
				furnace_minecart = true
				item_frame = true
				horse = true
				minecart = true
				ender_dragon = true
				leash_knot = true
				glow_squid = true
				warden = true
				glow_item_frame = true
				squid = true
				snowball = true
				shulker_bullet = true
				parrot = true
				creeper = true
				lightning_bolt = true
				enderman = true
				dragon_fireball = true
				chicken = true
				trader_llama = true
				donkey = true
				bogged = true
				chest_minecart = true
				tropical_fish = true
				fox = true
				slime = true
				pillager = true
				iron_golem = true
				zombified_piglin = true
				area_effect_cloud = true
				piglin = true
				blaze = true
				endermite = true
				cat = true
				zombie = true
				ender_pearl = true
				wind_charge = true
				breeze_wind_charge = true
				guardian = true
				ghast = true
				sheep = true
				fireball = true
				player = true
				pufferfish = true
				potion = true
				trident = true
				wither_skull = true
				wolf = true
				villager = true
				ominous_item_spawner = true
				zombie_villager = true
				elder_guardian = true
				chest_boat = true
				boat = true
				small_fireball = true
				strider = true
				hopper_minecart = true
				painting = true
				cave_spider = true
				witch = true
				cod = true
				snow_golem = true
				spider = true
				wither = true

